- name: custom hello_module
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: greet using custom module
      hello:
        name: Arpit
      register: result

    - name: show result
      debug:
        msg: "{{ result.message }}"
